name: HDTeam1
favicon: null
layout_spectrum: 0.023119500372558832
typography_spectrum: 0.5648315835278481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9501732881180942
  lightness: 0.5187800878193229
  saturation: 0.7182662077248096
  rhythmicContrast: 0.9410297437570989
purpose: []
